# version: '3.9'

services:
  app:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
#    environment:
#      - APP_ENV=local
    healthcheck:
      test: "curl -f http://localhost:8000/healthbeat/readiness || exit 1"
      interval: 10s
      retries: 15
      timeout: 3s
    volumes:
      - ./..:/usr/src/app
    network_mode: "host"
    environment:
      - "http_proxy=127.0.0.1:7890"
      - "https_proxy=127.0.0.1:7890"
